import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../src/components/Navbar'
import Hero from '../src/components/Hero'
import Models from '../src/components/Models'
import type { GetServerSideProps } from 'next'
import type { ModelsListIF } from '../src/interfaces'
import Footer from '../src/components/Footer'

type Props = {
  models: ModelsListIF[]
}

const Home: NextPage <Props> = ({models}) => {
  return (
    <div>
      <Head>
        <title>ego challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar models/>
      <Hero/>
      <Models models={models}/>
      <Footer/>
    </div>
  )
}

export default Home

export const getStaticProps:GetServerSideProps = async () => {
  const res = await fetch("https://challenge.agenciaego.tech/api/models/")
  const models = await res.json()
  return {
      props: {
          models
      }
  }
}
